version: '3.7'
services:
  envoy:
    image: envoyproxy/envoy:v1.25-latest
    ports:
        - ${HOST_ADMIN_PORT}:9901
        - ${HOST_HTTP_PORT}:80
        - ${HOST_HTTPS_PORT}:443
    restart: unless-stopped
    volumes:
        - ./envoy.yaml:/etc/envoy/envoy.yaml
